export const featuresHtml = `
<style>
  .feature-row { display: grid; grid-template-columns: 1fr 1fr; gap: 80px; align-items: center; padding: 80px 0; border-top: 1px solid var(--line-soft); }
  .feature-row:first-of-type { border-top: 0; }
  .feature-row.reverse > div:first-child { order: 2; }
  .feature-row h2 { font-size: clamp(28px, 3vw, 40px); }
  .feature-row .visual {
    position: relative; aspect-ratio: 4/5; border-radius: var(--r-xl);
    background: var(--bg-tint); padding: 32px;
    display: flex; align-items: center; justify-content: center;
    border: 1px solid var(--line-soft);
  }
  .feature-row ul { list-style: none; margin-top: 24px; display: flex; flex-direction: column; gap: 12px; }
  .feature-row ul li {
    display: flex; gap: 12px; align-items: flex-start; color: var(--fg-2); font-size: 15.5px; line-height: 1.55;
  }
  .feature-row ul li::before {
    content: ''; width: 18px; height: 18px; border-radius: 50%; background: color-mix(in oklch, var(--accent, var(--green)) 14%, transparent);
    flex-shrink: 0; margin-top: 2px;
    background-image: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='%232E7D32' stroke-width='3' stroke-linecap='round'><path d='M20 6 9 17l-5-5'/></svg>");
    background-size: 14px; background-repeat: no-repeat; background-position: center;
  }
  @media (max-width: 900px) {
    .feature-row { grid-template-columns: 1fr; gap: 32px; padding: 56px 0; }
    .feature-row.reverse > div:first-child { order: 0; }
    .feature-row .visual { aspect-ratio: 4/3; }
  }

  .mini-phone { width: 240px; aspect-ratio: 240/500; background: #0F0A07; border-radius: 36px; padding: 8px; box-shadow: 0 20px 40px -10px rgba(28,46,74,.3); }
  .mini-phone .screen { width: 100%; height: 100%; background: var(--bg); border-radius: 28px; overflow: hidden; position: relative; }

  .stack-grid {
    display: grid; grid-template-columns: repeat(5, 1fr); gap: 12px;
  }
  .stack-card {
    background: var(--surface); border: 1px solid var(--line-soft);
    border-radius: var(--r-md); padding: 24px 22px 22px;
    display: flex; flex-direction: column; gap: 8px;
    transition: border-color .15s ease, transform .15s ease;
    min-height: 132px;
  }
  .stack-card:hover { border-color: var(--navy); transform: translateY(-2px); }
  .stack-card .stack-num {
    font-family: var(--mono); font-size: 11px; color: var(--green);
    letter-spacing: .08em; font-weight: 600;
  }
  .stack-card .stack-name {
    font-size: 16px; font-weight: 700; color: var(--navy);
    letter-spacing: -0.01em; margin-top: 4px;
  }
  .stack-card .stack-detail {
    font-family: var(--mono); font-size: 12px; color: var(--fg-3);
    margin-top: auto; letter-spacing: .02em;
  }
  @media (max-width: 1100px) { .stack-grid { grid-template-columns: repeat(4, 1fr); } }
  @media (max-width: 900px)  { .stack-grid { grid-template-columns: repeat(3, 1fr); } }
  @media (max-width: 640px)  { .stack-grid { grid-template-columns: repeat(2, 1fr); } }
</style>

<!-- HERO -->
<section class="hero">
  <div class="wrap-narrow" style="text-align:center;">
    <span class="eyebrow"><span class="dot"></span><span data-es>Funciones</span><span data-en>Features</span></span>
    <h1 style="margin-top:24px;">
      <span data-es>Todo lo que necesitas para conocer Álamos a fondo.</span>
      <span data-en>Everything you need to truly know Álamos.</span>
    </h1>
    <p class="lede" style="margin:24px auto 0;">
      <span data-es>TrazaGo está pensada para el viajero curioso: el que quiere algo más profundo que una lista de "lugares populares".</span>
      <span data-en>TrazaGo is built for the curious traveler — the one who wants more than a "top 10 spots" list.</span>
    </p>
  </div>
</section>

<div class="wrap">

  <!-- AI ROUTES -->
  <div class="feature-row" id="ai" style="--accent: #2E7D32;">
    <div>
      <span class="tag"><span class="dot"></span><span data-es>Inteligencia Artificial</span><span data-en>AI</span></span>
      <h2 style="margin-top:16px;">
        <span data-es>Rutas generadas por Gemini, optimizadas para ti.</span>
        <span data-en>Routes generated by Gemini, optimized for you.</span>
      </h2>
      <p class="lede" style="margin-top:16px;">
        <span data-es>Cuatro pasos en un wizard responden cuatro preguntas: cuánto tiempo tienes, qué te interesa, a qué ritmo viajas y qué presupuesto manejas. La IA pre-filtra candidatos, los ordena, valida horarios y te entrega un itinerario listo.</span>
        <span data-en>A four-step wizard answers four questions: how much time, what interests you, your pace, your budget. The AI pre-filters candidates, orders them, validates hours, and hands you a ready itinerary.</span>
      </p>
      <ul>
        <li><span data-es>Pipeline de 6 etapas: pre-filtrado, prompt builder, generador, validador, optimizador, enriquecedor.</span><span data-en>6-stage pipeline: pre-filter, prompt builder, generator, validator, optimizer, enricher.</span></li>
        <li><span data-es>Editor drag-and-drop para reordenar paradas después de generar.</span><span data-en>Drag-and-drop editor to reorder stops after generation.</span></li>
        <li><span data-es>Regenera con un toque si algo no convence.</span><span data-en>Regenerate with one tap if something doesn't fit.</span></li>
      </ul>
    </div>
    <div class="visual">
      <div class="mini-phone">
        <div class="screen">
          <div style="padding:44px 14px 0;">
            <div style="font-size:11px;color:var(--fg-3);font-family:var(--mono);letter-spacing:.08em;text-transform:uppercase;">
              <span data-es>Paso 3 de 4</span><span data-en>Step 3 of 4</span>
            </div>
            <h3 style="font-size:18px;margin-top:8px;">
              <span data-es>¿Qué te interesa?</span><span data-en>What interests you?</span>
            </h3>
            <div style="display:flex;flex-direction:column;gap:6px;margin-top:14px;">
              <div style="padding:10px 12px;border-radius:10px;background:rgba(46,125,50,.12);border:1.5px solid #2E7D32;color:#2E7D32;font-size:12px;font-weight:600;display:flex;justify-content:space-between;align-items:center;">
                <span><span data-es>🏛️ Historia y arquitectura</span><span data-en>🏛️ History & architecture</span></span>
                <span>✓</span>
              </div>
              <div style="padding:10px 12px;border-radius:10px;background:#fff;border:1.5px solid var(--line);font-size:12px;color:var(--fg-2);">
                <span data-es>🎨 Arte y artesanías</span><span data-en>🎨 Art & crafts</span>
              </div>
              <div style="padding:10px 12px;border-radius:10px;background:rgba(46,125,50,.12);border:1.5px solid #2E7D32;color:#2E7D32;font-size:12px;font-weight:600;display:flex;justify-content:space-between;align-items:center;">
                <span><span data-es>🍴 Gastronomía local</span><span data-en>🍴 Local food</span></span>
                <span>✓</span>
              </div>
              <div style="padding:10px 12px;border-radius:10px;background:#fff;border:1.5px solid var(--line);font-size:12px;color:var(--fg-2);">
                <span data-es>🌳 Naturaleza</span><span data-en>🌳 Nature</span>
              </div>
              <div style="padding:10px 12px;border-radius:10px;background:#fff;border:1.5px solid var(--line);font-size:12px;color:var(--fg-2);">
                <span data-es>📸 Fotografía</span><span data-en>📸 Photography</span>
              </div>
            </div>
            <div style="position:absolute;bottom:18px;left:14px;right:14px;display:flex;gap:8px;">
              <button style="flex:1;padding:11px;border-radius:12px;background:#F4DED4;color:var(--fg-2);font-size:12px;font-weight:600;">
                <span data-es>Atrás</span><span data-en>Back</span>
              </button>
              <button style="flex:2;padding:11px;border-radius:12px;background:#2E7D32;color:#fff;font-size:12px;font-weight:600;">
                <span data-es>Siguiente</span><span data-en>Next</span>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- MAP -->
  <div class="feature-row reverse" id="map" style="--accent: #D93B3B;">
    <div>
      <span class="tag" style="--accent:#D93B3B;"><span class="dot"></span><span data-es>Mapa interactivo</span><span data-en>Interactive map</span></span>
      <h2 style="margin-top:16px;">
        <span data-es>180+ lugares, filtrados por lo que quieres encontrar.</span>
        <span data-en>180+ places, filtered by what you actually want.</span>
      </h2>
      <p class="lede" style="margin-top:16px;">
        <span data-es>Cada punto del mapa está categorizado, tiene fotos, horarios verificados y reseñas. Filtra por museos, restaurantes, hoteles, iglesias o parques con un toque.</span>
        <span data-en>Every map point is categorized — with photos, verified hours and reviews. Filter by museums, restaurants, hotels, churches or parks in one tap.</span>
      </p>
      <ul>
        <li><span data-es>Pins con código de color por categoría.</span><span data-en>Color-coded pins per category.</span></li>
        <li><span data-es>Bottom sheet con vista rápida y acceso a detalle.</span><span data-en>Bottom-sheet quick preview with link to full detail.</span></li>
        <li><span data-es>Navegación turn-by-turn integrada con Google Maps.</span><span data-en>Turn-by-turn navigation integrated with Google Maps.</span></li>
      </ul>
    </div>
    <div class="visual" style="background:#E8E0D8;">
      <svg width="100%" height="100%" viewBox="0 0 320 400" style="position:absolute;inset:0;border-radius:inherit;">
        <defs><pattern id="grid" width="32" height="32" patternUnits="userSpaceOnUse"><path d="M 32 0 L 0 0 0 32" fill="none" stroke="#221A15" stroke-width=".4" opacity=".15"/></pattern></defs>
        <rect width="320" height="400" fill="url(#grid)"/>
        <path d="M0 140 Q160 130 320 160" stroke="#221A15" stroke-width="8" fill="none" opacity=".22"/>
        <path d="M120 0 Q130 200 150 400" stroke="#221A15" stroke-width="6" fill="none" opacity=".22"/>
        <path d="M0 280 Q160 260 320 290" stroke="#221A15" stroke-width="5" fill="none" opacity=".18"/>
        <path d="M220 0 Q210 200 240 400" stroke="#221A15" stroke-width="5" fill="none" opacity=".18"/>
      </svg>
      <div style="position:absolute; top:60px; left:60px;">
        <div style="width:36px;height:36px;border-radius:50% 50% 50% 0;transform:rotate(-45deg);background:#9C27B0;display:flex;align-items:center;justify-content:center;box-shadow:0 3px 8px rgba(0,0,0,.25);">
          <div style="width:12px;height:12px;border-radius:50%;background:#fff;transform:rotate(45deg);"></div>
        </div>
      </div>
      <div style="position:absolute; top:180px; left:160px;">
        <div style="width:36px;height:36px;border-radius:50% 50% 50% 0;transform:rotate(-45deg);background:#FF5722;display:flex;align-items:center;justify-content:center;box-shadow:0 3px 8px rgba(0,0,0,.25);">
          <div style="width:12px;height:12px;border-radius:50%;background:#fff;transform:rotate(45deg);"></div>
        </div>
      </div>
      <div style="position:absolute; top:120px; right:60px;">
        <div style="width:36px;height:36px;border-radius:50% 50% 50% 0;transform:rotate(-45deg);background:#00BCD4;display:flex;align-items:center;justify-content:center;box-shadow:0 3px 8px rgba(0,0,0,.25);">
          <div style="width:12px;height:12px;border-radius:50%;background:#fff;transform:rotate(45deg);"></div>
        </div>
      </div>
      <div style="position:absolute; top:250px; right:90px;">
        <div style="width:36px;height:36px;border-radius:50% 50% 50% 0;transform:rotate(-45deg);background:#4CAF50;display:flex;align-items:center;justify-content:center;box-shadow:0 3px 8px rgba(0,0,0,.25);">
          <div style="width:12px;height:12px;border-radius:50%;background:#fff;transform:rotate(45deg);"></div>
        </div>
      </div>
      <div style="position:absolute; top:280px; left:90px;">
        <div style="width:36px;height:36px;border-radius:50% 50% 50% 0;transform:rotate(-45deg);background:#2196F3;display:flex;align-items:center;justify-content:center;box-shadow:0 3px 8px rgba(0,0,0,.25);">
          <div style="width:12px;height:12px;border-radius:50%;background:#fff;transform:rotate(45deg);"></div>
        </div>
      </div>

      <div style="position:absolute;top:20px;left:20px;right:20px;display:flex;gap:6px;overflow:hidden;">
        <span style="padding:6px 12px;border-radius:14px;background:var(--green);color:#fff;font-size:11px;font-weight:600;">Todos</span>
        <span style="padding:6px 12px;border-radius:14px;background:#fff;color:var(--fg);font-size:11px;font-weight:500;box-shadow:0 1px 4px rgba(0,0,0,.08);">Museos</span>
        <span style="padding:6px 12px;border-radius:14px;background:#fff;color:var(--fg);font-size:11px;font-weight:500;box-shadow:0 1px 4px rgba(0,0,0,.08);">Restaurantes</span>
        <span style="padding:6px 12px;border-radius:14px;background:#fff;color:var(--fg);font-size:11px;font-weight:500;box-shadow:0 1px 4px rgba(0,0,0,.08);">Hoteles</span>
      </div>
    </div>
  </div>

  <!-- PROXIMITY NOTIFICATIONS -->
  <div class="feature-row" id="proximity" style="--accent: #5CB8B2;">
    <div>
      <span class="tag" style="--accent:#5CB8B2;"><span class="dot"></span><span data-es>Geofencing</span><span data-en>Geofencing</span></span>
      <h2 style="margin-top:16px;">
        <span data-es>El pueblo te susurra cuando hay algo cerca.</span>
        <span data-en>The town whispers when something's near.</span>
      </h2>
      <p class="lede" style="margin-top:16px;">
        <span data-es>Geofencing real: cuando pasas a menos de 100 metros de un punto de interés, recibes un aviso discreto. Sin saturar, sin ads.</span>
        <span data-en>Real geofencing: when you walk within 100 m of a point of interest, you get a quiet alert. No clutter, no ads.</span>
      </p>
      <ul>
        <li><span data-es>Ajusta el radio y las categorías que te avisan.</span><span data-en>Tune the radius and which categories alert you.</span></li>
        <li><span data-es>Funciona en segundo plano sin consumir batería.</span><span data-en>Runs in the background without draining your battery.</span></li>
        <li><span data-es>Modo silencioso por horario.</span><span data-en>Quiet hours mode.</span></li>
      </ul>
    </div>
    <div class="visual">
      <div style="background:#fff;border-radius:18px;padding:18px;width:80%;box-shadow:0 12px 30px -8px rgba(28,46,74,.18); display:flex; gap:14px; align-items:flex-start;">
        <div style="width:42px;height:42px;border-radius:10px;background:#5CB8B214;display:flex;align-items:center;justify-content:center;flex-shrink:0;">
          <svg width="22" height="22" viewBox="0 0 24 24" fill="#5CB8B2"><path d="M12 2C8.13 2 5 5.13 5 9c0 5.25 7 13 7 13s7-7.75 7-13c0-3.87-3.13-7-7-7zm0 9.5c-1.38 0-2.5-1.12-2.5-2.5s1.12-2.5 2.5-2.5 2.5 1.12 2.5 2.5-1.12 2.5-2.5 2.5z"/></svg>
        </div>
        <div style="flex:1;">
          <div style="display:flex;justify-content:space-between;align-items:center;">
            <div style="font-size:11px;font-family:var(--mono);color:var(--fg-3);text-transform:uppercase;letter-spacing:.06em;">TrazaGo</div>
            <div style="font-size:11px;color:var(--fg-3);">14:32</div>
          </div>
          <div style="font-size:14px;font-weight:600;color:var(--navy);margin-top:4px;">
            <span data-es>Estás cerca de la Catedral</span><span data-en>You're near the Cathedral</span>
          </div>
          <div style="font-size:13px;color:var(--fg-2);margin-top:2px;line-height:1.4;">
            <span data-es>A 80 m. Está abierta hasta las 18:00. ¿Pasamos un momento?</span><span data-en>80 m away. Open until 6 PM. Want to stop by?</span>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- CHECK-INS & STATS -->
  <div class="feature-row reverse" id="checkins" style="--accent: #F59E0B;">
    <div>
      <span class="tag" style="--accent:#F59E0B;"><span class="dot"></span><span data-es>Memorias</span><span data-en>Memories</span></span>
      <h2 style="margin-top:16px;">
        <span data-es>Lleva tu trayecto contigo, mucho después.</span>
        <span data-en>Take your trip home with you, long after.</span>
      </h2>
      <p class="lede" style="margin-top:16px;">
        <span data-es>Cada check-in queda guardado con foto, hora y notas. Tu perfil muestra estadísticas, insignias por hitos, y un mapa de calor de tu paso por Álamos.</span>
        <span data-en>Every check-in is saved with photo, time and notes. Your profile shows stats, milestone badges, and a heatmap of your walk through Álamos.</span>
      </p>
      <ul>
        <li><span data-es>Insignias por categoría: Museos, Iglesias, Sabor de Sonora.</span><span data-en>Badges by category: Museums, Churches, Sonora Flavor.</span></li>
        <li><span data-es>Estadísticas detalladas con tiempo, distancia y favoritos.</span><span data-en>Detailed stats with time, distance, favorites.</span></li>
        <li><span data-es>Comparte tu ruta a cualquier red social.</span><span data-en>Share your route to any social platform.</span></li>
      </ul>
    </div>
    <div class="visual">
      <div style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:10px;width:100%;">
        <div style="background:#fff;border-radius:14px;padding:18px 12px;text-align:center;">
          <div style="font-size:28px;font-weight:700;color:var(--green);">12</div>
          <div style="font-size:11px;color:var(--fg-3);margin-top:4px;font-family:var(--mono);text-transform:uppercase;letter-spacing:.06em;">Check-ins</div>
        </div>
        <div style="background:#fff;border-radius:14px;padding:18px 12px;text-align:center;">
          <div style="font-size:28px;font-weight:700;color:var(--green);">8</div>
          <div style="font-size:11px;color:var(--fg-3);margin-top:4px;font-family:var(--mono);text-transform:uppercase;letter-spacing:.06em;"><span data-es>Favoritos</span><span data-en>Favorites</span></div>
        </div>
        <div style="background:#fff;border-radius:14px;padding:18px 12px;text-align:center;">
          <div style="font-size:28px;font-weight:700;color:var(--green);">3</div>
          <div style="font-size:11px;color:var(--fg-3);margin-top:4px;font-family:var(--mono);text-transform:uppercase;letter-spacing:.06em;"><span data-es>Rutas</span><span data-en>Routes</span></div>
        </div>
        <div style="grid-column:span 3;background:#fff;border-radius:14px;padding:16px;">
          <div style="font-size:13px;font-weight:600;color:var(--navy);margin-bottom:12px;">
            <span data-es>Insignias</span><span data-en>Badges</span>
          </div>
          <div style="display:flex;gap:10px;">
            <div style="width:48px;height:48px;border-radius:12px;background:#F4DED4;display:flex;align-items:center;justify-content:center;font-size:24px;">🏛️</div>
            <div style="width:48px;height:48px;border-radius:12px;background:#F4DED4;display:flex;align-items:center;justify-content:center;font-size:24px;">🗺️</div>
            <div style="width:48px;height:48px;border-radius:12px;background:#F4DED4;display:flex;align-items:center;justify-content:center;font-size:24px;">⭐</div>
            <div style="width:48px;height:48px;border-radius:12px;background:#F4E6DC;display:flex;align-items:center;justify-content:center;font-size:18px;color:var(--fg-3);">?</div>
            <div style="width:48px;height:48px;border-radius:12px;background:#F4E6DC;display:flex;align-items:center;justify-content:center;font-size:18px;color:var(--fg-3);">?</div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- EVENTS + BLOG + WEATHER -->
  <div class="feature-row" id="events" style="--accent: #9C27B0;">
    <div>
      <span class="tag" style="--accent:#9C27B0;"><span class="dot"></span><span data-es>Contenido fresco</span><span data-en>Fresh content</span></span>
      <h2 style="margin-top:16px;">
        <span data-es>Eventos, blog y clima — siempre al día.</span>
        <span data-en>Events, blog and weather — always current.</span>
      </h2>
      <p class="lede" style="margin-top:16px;">
        <span data-es>Un CMS interno mantiene los eventos del Festival Ortiz Tirado, las exposiciones temporales y los artículos sobre la historia y cultura de Álamos al día.</span>
        <span data-en>An internal CMS keeps Ortiz Tirado Festival events, temporary exhibitions and articles on Álamos's history and culture always up to date.</span>
      </p>
      <ul>
        <li><span data-es>Calendario semanal de eventos con filtros.</span><span data-en>Weekly events calendar with filters.</span></li>
        <li><span data-es>Blog editorial con artículos curados por historiadores locales.</span><span data-en>Editorial blog with articles curated by local historians.</span></li>
        <li><span data-es>Clima en tiempo real (OpenWeatherMap) con recomendaciones.</span><span data-en>Real-time weather (OpenWeatherMap) with recommendations.</span></li>
      </ul>
    </div>
    <div class="visual">
      <div style="display:flex;flex-direction:column;gap:10px;width:100%;">
        <div style="background:linear-gradient(135deg,#5CB8B2,#2E7D32);color:#fff;border-radius:14px;padding:14px 16px;display:flex;align-items:center;gap:12px;">
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#fff" stroke-width="2"><circle cx="12" cy="12" r="5"/><path d="M12 1v2M12 21v2M4.22 4.22l1.42 1.42M18.36 18.36l1.42 1.42M1 12h2M21 12h2M4.22 19.78l1.42-1.42M18.36 5.64l1.42-1.42"/></svg>
          <div style="flex:1;">
            <div style="font-size:20px;font-weight:700;">32°C</div>
            <div style="font-size:11px;opacity:.85;">Álamos · <span data-es>Soleado</span><span data-en>Sunny</span></div>
          </div>
        </div>
        <div style="background:#fff;border-radius:14px;padding:14px;display:flex;gap:12px;align-items:center;">
          <div style="width:54px;height:54px;border-radius:10px;background:#9C27B015;color:#9C27B0;display:flex;align-items:center;justify-content:center;flex-direction:column;flex-shrink:0;">
            <div style="font-size:9px;font-weight:600;text-transform:uppercase;letter-spacing:.06em;"><span data-es>ENE</span><span data-en>JAN</span></div>
            <div style="font-size:20px;font-weight:700;line-height:1;">22</div>
          </div>
          <div>
            <div style="font-size:13px;font-weight:600;color:var(--navy);"><span data-es>Festival Ortiz Tirado</span><span data-en>Ortiz Tirado Festival</span></div>
            <div style="font-size:11px;color:var(--fg-2);margin-top:2px;"><span data-es>Plaza de Armas · 20:00</span><span data-en>Plaza de Armas · 8 PM</span></div>
          </div>
        </div>
        <div style="background:#fff;border-radius:14px;padding:14px;display:flex;gap:12px;align-items:center;">
          <div style="width:54px;height:54px;border-radius:10px;background:#F4DED4;flex-shrink:0;background-image:repeating-linear-gradient(135deg,#F4DED4,#F4DED4 4px,#FBEFE7 4px,#FBEFE7 8px);"></div>
          <div>
            <div style="font-size:11px;color:#FF5722;font-weight:600;font-family:var(--mono);text-transform:uppercase;letter-spacing:.06em;">Blog</div>
            <div style="font-size:13px;font-weight:600;color:var(--navy);margin-top:2px;"><span data-es>10 secretos de las casonas de Álamos</span><span data-en>10 secrets of Álamos's colonial homes</span></div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- GUEST MODE -->
  <div class="feature-row reverse" id="guest" style="--accent: #1C2E4A;">
    <div>
      <span class="tag" style="--accent:#1C2E4A;"><span class="dot"></span><span data-es>Privacidad primero</span><span data-en>Privacy first</span></span>
      <h2 style="margin-top:16px;">
        <span data-es>Explora sin cuenta. Tus datos, tus reglas.</span>
        <span data-en>Explore without an account. Your data, your rules.</span>
      </h2>
      <p class="lede" style="margin-top:16px;">
        <span data-es>Modo invitado completo: explora el mapa, genera rutas, lee el blog y consulta eventos sin registrarte. Cuando quieras guardar favoritos o sincronizar dispositivos, registrarte toma 10 segundos.</span>
        <span data-en>Full guest mode: browse the map, generate routes, read the blog, check events without signing up. When you want to save favorites or sync devices, signup takes 10 seconds.</span>
      </p>
      <ul>
        <li><span data-es>Firebase App Check + reglas estrictas de Firestore.</span><span data-en>Firebase App Check + strict Firestore rules.</span></li>
        <li><span data-es>Sin tracking de terceros. Solo Crashlytics agregado.</span><span data-en>No third-party tracking. Only aggregated Crashlytics.</span></li>
        <li><span data-es>Tus rutas son tuyas — exportables, borrables.</span><span data-en>Your routes are yours — exportable, deletable.</span></li>
      </ul>
    </div>
    <div class="visual">
      <div style="background:#fff;border-radius:18px;padding:24px;width:80%;display:flex;flex-direction:column;gap:14px;box-shadow:0 12px 30px -8px rgba(28,46,74,.15);">
        <img src="assets/logo.jpeg" alt="" style="width:56px;height:56px;border-radius:12px;align-self:center;" />
        <div style="text-align:center;font-size:16px;font-weight:700;color:var(--navy);">TrazaGo</div>
        <div style="height:1px;background:var(--line-soft);"></div>
        <button style="padding:11px;border-radius:11px;background:var(--green);color:#fff;font-size:13px;font-weight:600;">
          <span data-es>Iniciar Sesión</span><span data-en>Sign In</span>
        </button>
        <button style="padding:11px;border-radius:11px;background:transparent;border:1.5px solid var(--green);color:var(--green);font-size:13px;font-weight:500;">
          <span data-es>Crear Cuenta</span><span data-en>Create Account</span>
        </button>
        <button style="background:none;color:var(--fg-2);font-size:13px;padding:6px;">
          <span data-es>Continuar como invitado →</span><span data-en>Continue as guest →</span>
        </button>
      </div>
    </div>
  </div>

</div>

<!-- STACK -->
<section id="stack" style="background:var(--bg-tint);">
  <div class="wrap">
    <div style="max-width:680px;margin-bottom:48px;">
      <span class="eyebrow"><span class="dot"></span><span data-es>Stack</span><span data-en>Stack</span></span>
      <h2 style="margin-top:20px;">
        <span data-es>Construido con</span><span data-en>Built with</span>
      </h2>
      <p class="lede" style="margin-top:16px;">
        <span data-es>Tecnología actual, decisiones conservadoras donde importa.</span>
        <span data-en>Modern tech, conservative decisions where it matters.</span>
      </p>
    </div>

    <div class="stack-grid">
      <div class="stack-card">
        <div class="stack-num">01</div>
        <div class="stack-name">Kotlin</div>
        <div class="stack-detail">2.0.21</div>
      </div>
      <div class="stack-card">
        <div class="stack-num">02</div>
        <div class="stack-name">Material 3</div>
        <div class="stack-detail">&nbsp;</div>
      </div>
      <div class="stack-card">
        <div class="stack-num">03</div>
        <div class="stack-name">Firebase</div>
        <div class="stack-detail">Auth · Firestore · Storage</div>
      </div>
      <div class="stack-card">
        <div class="stack-num">04</div>
        <div class="stack-name">Google Maps SDK</div>
        <div class="stack-detail">&nbsp;</div>
      </div>
      <div class="stack-card">
        <div class="stack-num">05</div>
        <div class="stack-name">Gemini</div>
        <div class="stack-detail">0.9.0</div>
      </div>
      <div class="stack-card">
        <div class="stack-num">06</div>
        <div class="stack-name">OpenWeather</div>
        <div class="stack-detail">API</div>
      </div>
      <div class="stack-card">
        <div class="stack-num">07</div>
        <div class="stack-name">Glide</div>
        <div class="stack-detail">4.16</div>
      </div>
      <div class="stack-card">
        <div class="stack-num">08</div>
        <div class="stack-name">OkHttp3</div>
        <div class="stack-detail">+ Coroutines</div>
      </div>
      <div class="stack-card">
        <div class="stack-num">09</div>
        <div class="stack-name">Crashlytics</div>
        <div class="stack-detail">Analytics</div>
      </div>
      <div class="stack-card">
        <div class="stack-num">10</div>
        <div class="stack-name">App Check</div>
        <div class="stack-detail">Play Integrity</div>
      </div>
    </div>
  </div>
</section>

<!-- CTA -->
<section>
  <div class="wrap">
    <div class="cta-band">
      <div>
        <h2><span data-es>Listo para trazar.</span><span data-en>Ready to trace.</span></h2>
        <p class="lede" style="margin-top:16px;">
          <span data-es>Descarga TrazaGo gratis. Sin tutoriales, sin paywall, sin ads.</span>
          <span data-en>Download TrazaGo free. No tutorials, no paywall, no ads.</span>
        </p>
      </div>
      <div style="display:flex;flex-direction:column;gap:12px;">
        <a href="download.html" class="btn btn-primary" style="background:#fff;color:var(--navy);justify-content:center;">App Store</a>
        <a href="download.html" class="btn btn-ghost" style="background:transparent;border-color:rgba(255,255,255,.3);color:#fff;justify-content:center;">Google Play</a>
      </div>
    </div>
  </div>
</section>
`;
